# Plugin params
solver_plugin: solver_plugins::CeresSolver
ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
ceres_preconditioner: SCHUR_JACOBI
ceres_trust_strategy: LEVENBERG_MARQUARDT
ceres_dogleg_type: TRADITIONAL_DOGLEG
ceres_loss_function: None

# ROS Parameters
odom_frame: odom
map_frame: map
base_frame: base_link
scan_topic: /scan_mapping
mode: mapping #localization
debug_logging: false
throttle_scans: 1
transform_publish_period: 0.01 #if 0 never publishes odometry
map_update_interval: 1.0
resolution: 0.025
max_laser_range: 40.0 #for rastering images
minimum_time_interval: 1.0
transform_timeout: 1.0
tf_buffer_duration: 100000.
stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
enable_interactive_mode: true
odom_topic: /odom
use_odom: true

# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.5
minimum_travel_heading: 0.5
scan_buffer_size: 120
scan_buffer_maximum_scan_distance: 120
link_match_minimum_response_fine: 0.7
link_scan_maximum_distance: 10.0
loop_search_maximum_distance: 20.0

do_loop_closing: true
transform_publish_period: 0.01
map_update_interval: 2.0
use_pose_graph: true
use_scan_matching: true
use_loop_closure: true
pose_graph_optimization_period: 1.0
serialization_interval: 0          # 중간 저장 비활성화
 
loop_match_minimum_chain_size: 4           
loop_match_maximum_variance_coarse: 3.0  
loop_match_minimum_response_coarse: 0.15    
loop_match_minimum_response_fine: 0.35
optimization_period: 1.0

# Correlation Parameters - Correlation Parameters
correlation_search_space_dimension: 0.5
correlation_search_space_resolution: 0.025
correlation_search_space_smear_deviation: 0.05

# Correlation Parameters - Loop Closure Parameters
loop_search_space_dimension: 10.0
loop_search_space_resolution: 0.025
loop_search_space_smear_deviation: 0.05

# Scan Matcher Parameters
distance_variance_penalty: 0.5      
angle_variance_penalty: 1.0    

fine_search_angle_offset: 0.00349     
coarse_search_angle_offset: 0.349   
coarse_angle_resolution: 0.01745
minimum_angle_penalty: 0.9
minimum_distance_penalty: 1.0
use_response_expansion: true
